adding ssh support for cron

diff --git a/sbin/autosyncer b/sbin/autosyncer
--- a/sbin/autosyncer
+++ b/sbin/autosyncer
@@ -26,6 +26,12 @@ else
 	_interval=8 #every 8 hour
 fi
 
+if [ ! -z "$SSH_AUTH_SOCK" ] ; then
+	echo "$SSH_AUTH_SOCK" > $_srcsbinpath/.store/agentpattern
+else
+	echo "	ERROR: No ssh-agent is currently running, unision might fail to connect remote servers automiatically without password" 1>&2
+fi
+
 if [ -f $_srcsbinpath/.store/paths.ok ] ; then
 	#write out current crontab
 	crontab -l > $_srcsbinpath/.store/mycron
diff --git a/sbin/syncer b/sbin/syncer
--- a/sbin/syncer
+++ b/sbin/syncer
@@ -43,6 +43,36 @@ else
 	readarray _paths < "$_srcsbinpath/.store/paths.ok"
 fi
 
+if [ -z "$SSH_AUTH_SOCK" ] ; then
+
+	if [ -z "$_sockpattern" ] &&  [ -f $_srcsbinpath/.store/agentpattern ]; then
+		_sockpattern=$(cat $_srcsbinpath/.store/agentpattern)
+	fi
+
+	if [ ! -z "$_sockpattern" ] ; then
+		_agentdir=""
+		_agent=""
+		if [ ${_sockpattern:0:9} != "/tmp/ssh-" ] ; then
+			_agentfilename=${_sockpattern##*/}
+			_agentpath=$(dirname $_sockpattern)
+			_basedirname=${_agentpath##*/}
+			_prefix=${_basedirname%%-*}
+			_basedir=$(dirname $_agentpath)
+			_myname="$(whoami)"
+			getnewest "${_basedir}" "${_prefix}-*" "_agentdir" "$_myname" && getnewest "$_agentdir" "$_agentfilename" "_agent" "$_myname"
+		elif [ ${_sockpattern:0:9} = "/tmp/ssh-" ] ; then
+			getnewest "/tmp" "ssh-" "_agentdir" "$_myname" && getnewest "$_agentdir" "agent" "_agent" "$_myname"
+		fi
+	
+		if [ ! -z "$_agent" ] ; then
+			SSH_AUTH_SOCK=$_agent
+			export SSH_AUTH_SOCK;
+		fi
+	fi
+fi
+
+
+
 for p in "${_paths[@]}"
 do
 	_pparts=($(echo "$p" | tr "|" " " ))
@@ -91,7 +121,15 @@ do
 					#if [ -z "$_unison"  ] ; then
 						#_unison=$(command -v unison)
 					#fi
-					#echo "file sync with ssh: ${_unison} -auto -silent -batch -ui text -sshargs -C -fat ${_spath} ${t}"				
+					#echo "file sync with ssh: ${_unison} -auto -silent -batch -ui text -sshargs -C -fat ${_spath} ${_tpath}"
+					#echo "authshock=$SSH_AUTH_SOCK"
+					#export SSH_AUTH_SOCK="/run/user/1000/keyring-Yv4IK7/ssh"
+					if [ -z "$SSH_AUTH_SOCK" ] ; then
+						echo "	ERROR: No ssh-agent is currently running for $(whoami), unision might fail to connect remote servers automiatically without password" 1>&2
+						continue
+					else
+						echo "$SSH_AUTH_SOCK" > $_srcsbinpath/.store/agentpattern
+					fi		
 					${_unison} -auto -silent -batch -ui text -sshargs -C -fat ${_spath} ${_tpath}
 				fi
 			fi	
@@ -129,7 +167,13 @@ do
 				#if [ -z "$_unison"  ] ; then
 					#_unison=$(command -v unison)
 				#fi
-				#echo "file sync with local: ${_unison} -auto -silent -batch -ui text -fat ${_spath} ${t}"
+				#echo "file sync with local: ${_unison} -auto -silent -batch -ui text -fat ${_spath} ${_tpath}"
+				if [ -z "$SSH_AUTH_SOCK" ] ; then
+					echo "	ERROR: No ssh-agent is currently running for $(whoami), unision might fail to connect remote servers automiatically without password" 1>&2
+					continue
+				else
+					echo "$SSH_AUTH_SOCK" > $_srcsbinpath/.store/agentpattern
+				fi
 				${_unison} -auto -silent -batch -ui text -fat ${_spath} ${_tpath}
 			fi
 		fi
diff --git a/sbin/syncprep b/sbin/syncprep
--- a/sbin/syncprep
+++ b/sbin/syncprep
@@ -101,6 +101,7 @@ declare -a _drivenotconfig
 _installfailed=0
 _relogineed=1
 _pathnotexist=0
+_sshagentexist=0
 for p in "${_paths[@]}"
 do
 	if [ "${p:0:1}" = "#" ] ; then
@@ -150,6 +151,13 @@ do
 					_installfailed=1
 					continue
 				fi
+			fi
+			
+			if [ -z "$SSH_AUTH_SOCK" ] ; then
+				_sshagentexist=1
+				continue
+			else
+				echo "$SSH_AUTH_SOCK" > $_srcsbinpath/.store/agentpattern
 			fi
 			
 			if [ ! -f "$_srcsbinpath/.store/binpaths.ok" ] || ! grep -q "_unison=$_unison$" "$_srcsbinpath/.store/binpaths.ok" ; then
@@ -215,6 +223,13 @@ do
 					continue
 				fi
 			fi
+			
+			if [ -z "$SSH_AUTH_SOCK" ] ; then
+				_sshagentexist=1
+				continue
+			else
+				echo "$SSH_AUTH_SOCK" > $_srcsbinpath/.store/agentpattern
+			fi
 
 			if [ ! -f "$_srcsbinpath/.store/binpaths.ok" ] || ! grep -q "_unison=$_unison$" "$_srcsbinpath/.store/binpaths.ok" ; then
 				echo "_unison=$_unison" >> "$_srcsbinpath/.store/binpaths.ok"
@@ -262,6 +277,12 @@ if [ "$_pathnotexist" -gt 0 ] ; then
 	_isflagged=1
 	echo
 	echo "	ERROR: Some $_pathnotexist paths not found in the system." 1>&2
+fi
+
+if [ "$_sshagentexist" -gt 0 ] ; then
+	_isflagged=1
+	echo
+	echo "	ERROR: No ssh-agent is currently running for $(whoami), unision might fail to connect remote servers automiatically without password" 1>&2
 fi
 
 if [ $_relogineed -eq 0 ] ; then
