adding dependency resolver

diff --git a/sbin/drivesetup b/sbin/drivesetup
--- a/sbin/drivesetup
+++ b/sbin/drivesetup
@@ -27,8 +27,12 @@ if [ -s "$_srcsbinpath/.store/binpaths.ok" ] ; then
 	. $_srcsbinpath/.store/binpaths.ok		
 fi
 
+
 if [ -s "$_srcsbinpath/functions" ] ; then
 	. $_srcsbinpath/functions	
+else
+	echo "$_srcsbinpath/functions file not found!" 1>&2
+	exit 1
 fi
 
 if [ -z "$_skicka"  ] ; then
diff --git a/sbin/functions b/sbin/functions
--- a/sbin/functions
+++ b/sbin/functions
@@ -13,25 +13,12 @@
 #You should have received a copy of the GNU General Public License
 #along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-
-if [ ! -z "$_srcsbinpath" ]; then
-	_miscpath="$_srcsbinpath/.store/linux-misc"
-	if [ -s "$_miscpath" ] ; then
-		. "$_miscpath"
-	fi
-	
-	if ! _calloutput=$(addmiscpath "sshsetup" "$_sshsetup") ; then
-		echo "$_calloutput" 1>&2
-		exit 1
+if [ ! -z "$_srcsbinpath" ] ; then
+	if [ -s "$_srcsbinpath/resolve" ] ; then
+		. $_srcsbinpath/resolve	
 	else
-		_sshsetup="$_calloutput"
-	fi
-
-	if ! _calloutput=$(addmiscpath "githublatest" "$_githublatest") ; then
-		echo "$_calloutput" 1>&2
+		echo "$_srcsbinpath/resolve file not found!" 1>&2
 		exit 1
-	else
-		_githublatest="$_calloutput"
 	fi
 fi
 
diff --git a/sbin/syncer b/sbin/syncer
--- a/sbin/syncer
+++ b/sbin/syncer
@@ -41,6 +41,9 @@ fi
 
 if [ -s "$_srcsbinpath/functions" ] ; then
 	. $_srcsbinpath/functions	
+else
+	echo "$_srcsbinpath/functions file not found!" 1>&2
+	exit 1
 fi
 
 if [ ! -f "$_srcsbinpath/.store/paths.ok" ] ; then
