updating function, resolve, log deletion size, skicka update backup

diff --git a/sbin/functions b/sbin/functions
--- a/sbin/functions
+++ b/sbin/functions
@@ -217,4 +217,153 @@ function processdrivepath(){
 	fi
 }
 
+function golanginstalled(){
+	
+	local _loc _verline
+	_loc=$_go
+	
+	if [ -z "$_loc" ] ; then
+		 _loc=$(isinstalled "go" "$_go")
+	fi
+	
+	if [ -z "$_loc" ] && [ -x "/usr/local/go/bin/go" ] ; then
+		_loc="/usr/local/go/bin/go"
+	fi
+	
+	if [ ! -z "$_loc" ] && [ -x "$_loc" ] && $(echo $($_loc version) | grep -q "go version go") ; then
+		_go="$_loc"
+		echo "$_loc"
+		return 0
+	fi
+	
+	return 1
+
+}
+
+_goversion="1.4.2"
+function installgo()
+{
+	local pkgname failedmsg retval dirtoinstall golanghome grepline
+	failedmsg="go lang auto install failed!! to continue please try instruction in http://golang.org/doc/install"
+	pkgname="go${_goversion}.linux-${_osarch}.tar.gz"
+	bashrcfile=$(eval echo ~/.bashrc)
+	bashrcfileescaped=${thep//\//\\/}
+	retval=1
+
+	if ! golanginstalled ; then
+		if [ $_debianbased -eq 0 ] ; then
+			
+			if ! _wget=$(isinstalled "wget" "$_wget") ; then
+				if ! installpkg "wget" 0 "'wget' $_installconfirmmsg" ; then
+					_installfailed=1
+					return 1
+				fi		
+			fi
+			
+			if ! golanghome=$(confirmtogo "Default go language home directory: $(eval echo ~/.gohome) . Please type a custom directory or press only enter to take the default directory: " "notempty") ; then
+				golanghome=$(eval echo ~/.gohome)
+			fi
+			
+			if [ ! -e "$golanghome" ] ; then
+				sudo mkdir -p "$golanghome"
+				sudo chown $(id -u):$(id -g) "$golanghome"
+				if [ $? -ne 0 ] ; then
+					echo " ERROR: Go Language home directory $golanghome can't be created" 1>&2
+					return 1
+				fi
+			fi
+			
+			if ! dirtoinstall=$(confirmtogo "Default go language install directory: /usr/local . Please type a custom directory or press only enter to take the default directory: " "notempty") ; then
+				dirtoinstall="/usr/local"
+			fi
+			
+			if [ ! -e "$dirtoinstall" ] ; then
+				sudo mkdir -p "$dirtoinstall"
+				if [ $? -ne 0 ] ; then
+					echo " ERROR: Go Language install directory $dirtoinstall can't be created" 1>&2
+					return 1
+				fi
+			fi
+			
+			_curpath="$PWD"
+			rm -rf /tmp/$pkgname
+			sudo rm -rf "$dirtoinstall/go"
+			cd /tmp
+
+			$_wget --no-check-certificate "https://storage.googleapis.com/golang/$pkgname" -O "$pkgname" || ( cd $_curpath && echo "$failedmsg" 1>&2 && return 1 )
+			sudo tar -C "$dirtoinstall" -xzf $pkgname || ( cd $_curpath && echo "$failedmsg" 1>&2 && sudo rm -rf "$dirtoinstall/go" && return 1 )
+			sudo rm -rf $pkgname
+			cd $_curpath
+			export PATH="$PATH:$dirtoinstall/go/bin"
+			export GOPATH="$golanghome"
+			export PATH="$PATH:$golanghome/bin"
+			_go="$dirtoinstall/go/bin/go"
+			if ! grepline=$(grep -F "export PATH=\$PATH:$dirtoinstall/go/bin" ~/.bashrc) ; then
+				sudo sed -i -e '$a\' ~/.bashrc
+				echo "export PATH=\$PATH:$dirtoinstall/go/bin" >> ~/.bashrc	|| ( echo "$failedmsg" 1>&2 && sudo rm -rf "$dirtoinstall/go" && return 1 )
+			else
+				if [ "${grepline:0:1}" = "#" ] ; then
+					replaceline "$(escapepath "export PATH=\$PATH:$dirtoinstall/go/bin")" "export PATH=\$PATH:$dirtoinstall/go/bin" "$(eval echo ~/.bashrc)"
+				fi
+			fi
+			if ! grepline=$(grep -F "export GOPATH=$golanghome" ~/.bashrc) ; then
+				sed -i -e '$a\' ~/.bashrc
+				echo "export GOPATH=$golanghome" >> ~/.bashrc || ( echo "$failedmsg" 1>&2 && sudo rm -rf "$dirtoinstall/go" && return 1 )
+			else
+				if [ "${grepline:0:1}" = "#" ] ; then
+					replaceline "$(escapepath "export GOPATH=$golanghome")" "export GOPATH=$golanghome" "$(eval echo ~/.bashrc)"
+				fi
+			fi
+			if ! grepline=$(grep -F "export PATH=\$PATH:$golanghome/bin" ~/.bashrc) ; then
+				sed -i -e '$a\' ~/.bashrc
+				echo "export PATH=\$PATH:$golanghome/bin" >> ~/.bashrc || ( echo "$failedmsg" 1>&2 && sudo rm -rf "$dirtoinstall/go" && return 1 )
+			else
+				if [ "${grepline:0:1}" = "#" ] ; then
+					replaceline "$(escapepath "export PATH=\$PATH:$golanghome/bin")" "export PATH=\$PATH:$golanghome/bin" "$(eval echo ~/.bashrc)"
+				fi
+			fi
+			installpkg "git mercurial" || ( echo "$failedmsg" 1>&2 && sudo rm -rf "$dirtoinstall/go" && return 1 )
+			retval=0;		
+		fi
+	else
+		if [ ! -z "$_go" ] ; then
+			if ! grepline=$(grep -F "export PATH=\$PATH:$(dirname $_go)" ~/.bashrc) ; then
+				sudo sed -i -e '$a\' ~/.bashrc
+				echo "export PATH=\$PATH:$(dirname $_go)" >> ~/.bashrc || ( echo "$failedmsg" 1>&2 && sudo rm -rf /usr/local/go && return 1 )
+			else
+				if [ "${grepline:0:1}" = "#" ] ; then
+					replaceline "$(escapepath "export PATH=\$PATH:$(dirname $_go)")" "export PATH=\$PATH:$(dirname $_go)" "$(eval echo ~/.bashrc)"
+				fi
+			fi
+			if [ -z "$GOPATH" ] ; then
+				golanghome=$(eval echo ~/.gohome)
+				export GOPATH="$golanghome"
+			else
+				golanghome="$GOPATH"
+			fi
+			export PATH=$PATH:"$golanghome/bin"
+			if ! grepline=$(grep -F "export GOPATH=$golanghome" ~/.bashrc) ; then
+					sed -i -e '$a\' ~/.bashrc
+					echo "export GOPATH=$golanghome" >> ~/.bashrc
+			else
+				if [ "${grepline:0:1}" = "#" ] ; then
+					replaceline "$(escapepath "export GOPATH=$golanghome")" "export GOPATH=$golanghome" "$(eval echo ~/.bashrc)"
+				fi
+			fi
+			if ! grepline=$(grep -F "export PATH=\$PATH:$golanghome/bin" ~/.bashrc) ; then
+					sed -i -e '$a\' ~/.bashrc
+					echo "export PATH=\$PATH:$golanghome/bin" >> ~/.bashrc
+			else
+				if [ "${grepline:0:1}" = "#" ] ; then
+					replaceline "$(escapepath "export PATH=\$PATH:$golanghome/bin")" "export PATH=\$PATH:$golanghome/bin" "$(eval echo ~/.bashrc)"
+				fi
+			fi
+			retval=0;
+		else
+			retval=1;
+		fi
+	fi
+	return $retval;
+}
+
 
